### ISSUE TITLE
SB Checksum Review Actions

### ISSUE THREAD

**Issue by susheel** [ga4gh-schemablocks/sb-checksum#1]
- [ ] Search for ontologies that represent hash algorithms. If not found, use CSV list
- [x] Rename `type` to `hash_algorithm` with enum type.
- [x] List/point to hash algorithm ontology or CSV file
- [x] Upgrade to 0.0.2

**Comment by mbaudis** [comment]
@susheel Thinking about this a bit, I guess the specifications could be in a YAML/JSON document, where each checksum type is an object; and these objects are "oneOf" referenced to from the wrapper.

```
checksumType:
  $ref: ___url_to_list_of_ checksums___
```

```
checksums:
  - name: "sha-256"
    bitLength: 256
    reference:
      label: "RFC6920"
      url: http://www.iana.org/go/rfc6920
  - name: "etag"
    bitLength: 128
...
```

Not exactly, but in spirit, I guess?
